tsubuyaki/config/routes.rb
Rails.application.routes.draw do
  resources :tsubuyakies, :except => :new do #newへのルーティングを除く
     collection do
       post :confirm  #confirmへのルーティング
       get :profile   #profileへのルーティング
     end
   end
end

tsubuyaki/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

tsubuyaki/app/models/toukou.rb
class Toukou < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }
end

tsubuyaki/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

tsubuyaki/app/controllers/tsubuyakies_controller.rb
class TsubuyakiesController < ApplicationController
  before_action :set_tsubuyaki, only: [:show, :edit, :update,:destroy]

  # つぶやき一覧を表示するアクション
  def index
    @tsubuyakies = Toukou.all.order(created_at: "DESC")
    @tsubuyaki = Toukou.new
  end

  # つぶやきの詳細を確認するアクション
  def show
  end

  # つぶやきを登録するアクション
  def create
    @tsubuyaki = Toukou.new(tsubuyaki_params)
    if params[:back]
      @tsubuyakies = Toukou.all.order(created_at: "DESC")
      render :index
    else
      if @tsubuyaki.save
        redirect_to tsubuyakies_path, notice: "つぶやきました！"
      else
        @tsubuyakies = Toukou.all.order(created_at: "DESC")
        render action: :index
      end
    end
  end

  # つぶやき内容を編集するアクション
  def edit
  end

  #アップデートアクション
  def update
      if @tsubuyaki.update(tsubuyaki_params)
        redirect_to tsubuyakies_path, notice: "つぶやきを編集しました！"
      else
        render :edit
      end
    end

    #削除機能
    def destroy
      @tsubuyaki.destroy
      redirect_to tsubuyakies_path, notice:"つぶやきを削除しました！"
    end

    #登録前に確認するアクション
    def confirm
      @tsubuyaki = Toukou.new(tsubuyaki_params)
      if @tsubuyaki.invalid? then
        @tsubuyakies = Toukou.all.order(created_at: "DESC")
        render :index
      end
    end

    # プロフィールページへのアクション
    def profile
    end

  private

  def tsubuyaki_params
    params.require(:toukou).permit(:content)
  end

  def set_tsubuyaki
   @tsubuyaki = Toukou.find(params[:id])
  end

end

tsubuyaki/app/helpers/application_helper.rb
module ApplicationHelper
end

tsubuyaki/app/helpers/tsubuyakies_helper.rb
module TsubuyakiesHelper
  def choose_new_or_edit
    if action_name == 'confirm' || action_name == 'create' || action_name == 'index'
      confirm_tsubuyakies_path
    elsif action_name == 'edit'
      tsubuyaky_path
    end
  end
end

tsubuyaki/app/views/layouts/application.html.erb
<!-- 共通レイアウト画面 -->
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>Tsubuyaki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- ヘッダー -->
    <header class ="header clearfix">
      <div class="header-container">
        <a id="logo" href="/tsubuyakies">つぶやきアプリ</a>
        <nav class="global-nav">
          <ul>
            <li><a href="/tsubuyakies/profile">プロフィール</a></li>
          </ul>
        </nav>
      </div>
    </header>

    <!-- 本文 -->
    <%= yield %>

    <!-- フッター -->
    <footer>
      <div class="footer-content">
        <p>つぶやき株式会社</p>
        <p>©2019 Copyright Tsubuyaki Corp.</p>
      </div>
    </footer>
  </body>
</html>

tsubuyaki/app/views/tsubuyakies/_form.html.erb
<!-- 共通フォーム画面 -->
<%= form_with(model: @tsubuyaki, local:true, url: choose_new_or_edit) do |form| %>
  <% if @tsubuyaki.errors.any? %>
  <div id="error_explanation">
    <h2><%= @tsubuyaki.errors.count %>件のエラーがあります。</h2>
    <ul>
      <% @tsubuyaki.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="tsubuyaki_content">
  <%= form.text_area :content %>
</div>
<div class="submit_btn">
  <%= form.submit "POST"%>
</div>
<% end %>

tsubuyaki/app/views/tsubuyakies/confirm.html.erb
<div class="wrapper clearfix">
  <div class="sub-container">
    <h2>以下の内容で、送信する。</h2>
    <%= form_with(model: @tsubuyaki, url: tsubuyakies_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <p>つぶやき:<%= @tsubuyaki.content %></p>
    <p><%= form.submit  "登録する" %></p>
    <p><%= form.submit "戻る", name: 'back' %></p>
    <% end %>
  </div>
</div>

tsubuyaki/app/views/tsubuyakies/edit.html.erb
<!-- つぶやき編集画面 -->
<div class="wrapper clearfix">
  <div class="sub-container">
    <h2>つぶやきを編集する</h2>
    <%= render 'form' %>
    <div class="back_index">
      <%= link_to "つぶやき一覧画面にもどる", tsubuyakies_path %>
    </div>
  </div>
</div>

tsubuyaki/app/views/tsubuyakies/index.html.erb
<!-- つぶやきトップページ -->
<div class="wrapper clearfix">
  <div class="sidemenu">
    <section class="user-info">
      <%= image_tag('profile.jpg') %>
      <h2>Cat Taro</h2>
      <span><a href="/tsubuyakies/profile">View Profile</a></span>
    </section>
    <section>
      <div class="stat">
        <span>50 Following</span>
        <span>100 Followers</span>
      </div>
    </section>
    <section class="micro-post">
      <%= render 'form' %>
    </section>
  </div>
  <div class="main">
    <h3>つぶやき一覧</h3>
    <p><%= notice %></p>
    <!-- つぶやき一覧を表示する -->
    <ul class = "tweets">
    <% @tsubuyakies.each {|tsubuyaki| %>
      <li class="tweet">
        <div class="tweet-content">
          <%= image_tag('profile.jpg') %>
          <span class="tweet-tsubuyaki"><%= tsubuyaki.content %></span>
          <span class="create_date"><%= tsubuyaki.created_at %></span>
          <%= link_to '詳細', tsubuyaky_path(tsubuyaki.id) %>
          <%= link_to '編集', edit_tsubuyaky_path(tsubuyaki.id),data: { confirm: '本当に編集していいですか？' }  %>
          <%= link_to '削除', tsubuyaky_path(tsubuyaki.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %>
        </div>
      </li>
    <% } %>
    </ul>
  </div>
</div>

tsubuyaki/app/views/tsubuyakies/profile.html.erb
<!--プロフィール画面 -->
<div class="wrapper clearfix">
  <div class="sub-container">
    <h2>プロフィール</h2>
    <div class="profile_info">
      <%= image_tag('profile.jpg') %>
      <ul>
        <li>ユーザ名:Cat Taro</li>
        <li>生年月日:2019/11/01</li>
      </ul>
    </div>
    <div class="back_index">
      <%= link_to "つぶやき一覧画面にもどる", tsubuyakies_path %>
    </div>
  </div>
</div>

tsubuyaki/app/views/tsubuyakies/show.html.erb
<!-- つぶやき詳細画面 -->
<div class="wrapper clearfix">
    <div class="sub-container">
      <h2>つぶやき詳細画面</h2>
      <p>つぶやき: <%= @tsubuyaki.content %></p>
      <p>投稿日: <%= @tsubuyaki.created_at %></p>
      <%= link_to "つぶやき一覧画面にもどる", tsubuyakies_path %>
    </div>
</div>